# Copyright Header Check
# This workflow ensures all source files have proper copyright headers

name: Copyright Header Check

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [develop, master, main]

jobs:
  copyright-check:
    runs-on: ubuntu-latest
    # Skip if:
    # 1. PR is from github-actions bot (prevent infinite loops)
    # 2. This is the Copyright/CopyrightAdder repo itself
    if: |
      github.actor != 'github-actions[bot]' && 
      github.actor != 'dependabot[bot]' &&
      github.repository != 'roku674/Copyright' &&
      github.repository != 'roku674/CopyrightAdder'
    permissions:
      contents: write
      pull-requests: write
      actions: write
    
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Update Copyright Workflow (if submodule)
        run: |
          # Check if we're in a submodule context by looking for CopyrightAdder directory
          if [ -d "CopyrightAdder" ] || [ -d "Copyright" ]; then
            echo "Detected submodule context - updating parent workflow"
            
            # Ensure .github/workflows directory exists
            mkdir -p .github/workflows
            
            # Download latest workflow template
            curl -sSL https://raw.githubusercontent.com/roku674/Copyright/main/CopyrightAdder/copyright-check-template.yml -o .github/workflows/copyright-check.yml.tmp
            
            # Check if workflow file exists and differs
            if [ ! -f ".github/workflows/copyright-check.yml" ] || ! cmp -s ".github/workflows/copyright-check.yml" ".github/workflows/copyright-check.yml.tmp"; then
              echo "Updating copyright-check.yml workflow"
              mv .github/workflows/copyright-check.yml.tmp .github/workflows/copyright-check.yml
              git add .github/workflows/copyright-check.yml
            else
              echo "Workflow is up to date"
              rm .github/workflows/copyright-check.yml.tmp
            fi
            
            # Note: sources.txt is project-specific and should not be auto-updated
          fi
      
      - name: Setup Copyright Adder
        run: |
          # Check if CopyrightAdder exists as submodule, otherwise download
          if [ -d "CopyrightAdder" ]; then
            echo "Using existing CopyrightAdder submodule"
            chmod +x CopyrightAdder/add_copyright_headers.sh
          elif [ -d "Copyright/CopyrightAdder" ]; then
            echo "Using existing Copyright/CopyrightAdder submodule"
            chmod +x Copyright/CopyrightAdder/add_copyright_headers.sh
          else
            echo "Downloading CopyrightAdder"
            mkdir -p CopyrightAdder
            curl -sSL https://raw.githubusercontent.com/roku674/Copyright/main/CopyrightAdder/add_copyright_headers.sh -o CopyrightAdder/add_copyright_headers.sh
            curl -sSL https://raw.githubusercontent.com/roku674/Copyright/main/CopyrightAdder/sources.txt -o CopyrightAdder/sources.txt
            chmod +x CopyrightAdder/add_copyright_headers.sh
          fi
      
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v40
        with:
          files: |
            **/*.{java,js,ts,jsx,tsx,cpp,cc,c,h,cs,py,go,rs,rb,php,sh,yaml,yml,json,xml,html,sql}
      
      - name: Run Copyright Adder on changed files
        if: steps.changed-files.outputs.any_changed == 'true'
        env:
          CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          echo "Adding copyright headers to changed files..."
          
          # Determine script path based on submodule structure
          if [ -d "CopyrightAdder" ]; then
            SCRIPT_PATH="./CopyrightAdder/add_copyright_headers.sh"
          elif [ -d "Copyright/CopyrightAdder" ]; then
            SCRIPT_PATH="./Copyright/CopyrightAdder/add_copyright_headers.sh"
          else
            echo "Error: Could not find CopyrightAdder script"
            exit 1
          fi
          
          for file in $CHANGED_FILES; do
            if [ -f "$file" ]; then
              echo "Processing: $file"
              $SCRIPT_PATH "$file"
            fi
          done
      
      - name: Check for changes
        id: check-changes
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            echo "changes=true" >> $GITHUB_OUTPUT
            echo "Files missing copyright headers were found and updated."
            
            # List changed files for the PR description
            echo "changed_files<<EOF" >> $GITHUB_OUTPUT
            git status --porcelain | grep -E "^\s*M" | cut -c 4-
            echo "EOF" >> $GITHUB_OUTPUT
          else
            echo "changes=false" >> $GITHUB_OUTPUT
            echo "All files have proper copyright headers."
          fi
      
      - name: Check for workflow updates
        id: check-workflow-updates
        run: |
          # Check if there are any workflow updates to commit
          if [[ -n $(git status --porcelain .github/workflows/copyright-check.yml 2>/dev/null) ]]; then
            echo "workflow_changes=true" >> $GITHUB_OUTPUT
            echo "Workflow updates detected"
          else
            echo "workflow_changes=false" >> $GITHUB_OUTPUT
            echo "No workflow updates needed"
          fi
      
      - name: Create new branch for copyright headers
        if: steps.check-changes.outputs.changes == 'true' || steps.check-workflow-updates.outputs.workflow_changes == 'true'
        id: create-branch
        run: |
          # Generate unique branch name
          TIMESTAMP=$(date +%Y%m%d%H%M%S)
          NEW_BRANCH="copyright-headers/${{ github.head_ref }}-${TIMESTAMP}"
          echo "branch_name=${NEW_BRANCH}" >> $GITHUB_OUTPUT
          
          # Create and checkout new branch
          git checkout -b "${NEW_BRANCH}"
          
          # Commit changes
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add -A
          
          # Create appropriate commit message based on what changed
          if [[ "${{ steps.check-changes.outputs.changes }}" == "true" && "${{ steps.check-workflow-updates.outputs.workflow_changes }}" == "true" ]]; then
            git commit -m "Add copyright headers and update workflow"
          elif [[ "${{ steps.check-changes.outputs.changes }}" == "true" ]]; then
            git commit -m "Add copyright headers to source files"
          else
            git commit -m "Update copyright workflow"
          fi
          
          # Push the new branch
          git push origin "${NEW_BRANCH}"
      
      - name: Create Pull Request
        if: steps.check-changes.outputs.changes == 'true' || steps.check-workflow-updates.outputs.workflow_changes == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            const branchName = '${{ steps.create-branch.outputs.branch_name }}';
            const baseBranch = '${{ github.head_ref }}';
            const changedFiles = `${{ steps.check-changes.outputs.changed_files }}`;
            const hasCodeChanges = '${{ steps.check-changes.outputs.changes }}' === 'true';
            const hasWorkflowChanges = '${{ steps.check-workflow-updates.outputs.workflow_changes }}' === 'true';
            
            let prTitle = '';
            let prBody = '';
            
            if (hasCodeChanges && hasWorkflowChanges) {
              prTitle = `Add copyright headers and update workflow for ${baseBranch}`;
              prBody = `## Copyright Headers Added + Workflow Updated
              
              This automated pull request adds missing copyright headers to source files and updates the copyright workflow in the \`${baseBranch}\` branch.
              
              ### Changed Files:
              \`\`\`
              ${changedFiles}
              \`\`\`
              
              ### Updates:
              - Added missing copyright headers to source files
              - Updated .github/workflows/copyright-check.yml to latest version
              
              ### Notes:
              - This PR was automatically generated by the Copyright Header Check workflow
              - Please review the changes before merging
              - This PR targets the source branch \`${baseBranch}\`, not the base branch
              
              ---
              *Generated by GitHub Actions*`;
            } else if (hasCodeChanges) {
              prTitle = `Add copyright headers to ${baseBranch}`;
              prBody = `## Copyright Headers Added
              
              This automated pull request adds missing copyright headers to source files in the \`${baseBranch}\` branch.
              
              ### Changed Files:
              \`\`\`
              ${changedFiles}
              \`\`\`
              
              ### Notes:
              - This PR was automatically generated by the Copyright Header Check workflow
              - Please review the changes before merging
              - This PR targets the source branch \`${baseBranch}\`, not the base branch
              
              ---
              *Generated by GitHub Actions*`;
            } else {
              prTitle = `Update copyright workflow for ${baseBranch}`;
              prBody = `## Copyright Workflow Updated
              
              This automated pull request updates the copyright workflow in the \`${baseBranch}\` branch.
              
              ### Updates:
              - Updated .github/workflows/copyright-check.yml to latest version
              
              ### Notes:
              - This PR was automatically generated by the Copyright Header Check workflow
              - Please review the changes before merging
              - This PR targets the source branch \`${baseBranch}\`, not the base branch
              
              ---
              *Generated by GitHub Actions*`;
            }
            
            const pr = await github.rest.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: prTitle,
              body: prBody,
              head: branchName,
              base: baseBranch,
              labels: ['copyright', 'automated']
            });
            
            console.log(`Created PR #${pr.data.number}: ${pr.data.html_url}`);
            
            // Add comment to original PR
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: `⚠️ **Missing Copyright Headers Detected**\n\nI've created PR #${pr.data.number} to add missing copyright headers to your branch. Please review and merge it into your branch before this PR can be merged.`
            });
      
      - name: Clean up
        if: always()
        run: |
          rm -rf CopyrightAdder